### ISSUE TITLE
I`m not able to use ngx/alerts module with angular5-universal

### ISSUE THREAD

**Issue by gopalj** [ngx-plus/ngx-alerts#11]
**I`m not able to use ngx-alerts module with angular5-universal** 
since the document keyword is used in ngx-alerts
```

/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:151107
    var testEl = document.createElement('div');
                          ^

ReferenceError: document is not defined
    at /Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:151107:27
    at Object.VERSION (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:151120:3)
    at __webpack_require__ (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:20:30)
    at Object.ro6N (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:125614:638746)
    at n (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:125614:149)
    at Object.wQAS (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:125614:648626)
    at n (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:125614:149)
    at Object.aR8+ (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:125614:466540)
    at n (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:125614:149)
    at Object.bNRb (/Users/gopal.jayaraman/workspace/website/web_v3/dist/server.js:125614:481840)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! halodoc@3.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the halodoc@3.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gopal.jayaraman/.npm/_logs/2017-11-21T06_27_46_820Z-debug.log

```

**Comment by brannon-darby** [comment]
hi @gopalj - thanks for reaching out.  are you able to provide a minimal reproduction of the issue?
